export enum zIndexEnum {
  // HEADER and NAVIGATION has big number avoid z-index tooltip  collision with them
  HEADER_PAGE = 999999999,
  BREAD_CRUMB_NAVIGATION = 99999999,
  SMALL_ICON_AVATAR_WITH_ICON_COMPONENT = 4,
  OVERLAY_MOBILE_TOOLTIP = 4,
  CORE_UNIT_SUMMARY = 3,
  DELEGATE_SUMMARY = 3,
  NAVIGATION_CARDS = 2,
}
