export enum zIndexEnum {
  HEADER_PAGE = 10,
  BREAD_CRUMB_NAVIGATION = 8,
  OVERLAY_MOBILE_TOOLTIP = 8,
  ECHART_TOOL_TIP = 6,
  SMALL_ICON_AVATAR_WITH_ICON_COMPONENT = 4,
  CORE_UNIT_SUMMARY = 3,
  DELEGATE_SUMMARY = 3,
  NAVIGATION_CARDS = 2,
}
