export interface FeatureFlagsInterface {
  FEATURE_CARD_NAVIGATION: boolean;
  FEATURE_SITEMAP: boolean;
  FEATURE_TRANSPARENCY_NEW_TABLE: boolean;
  FEATURE_CU_INDEX_NEW_TABLE: boolean;
  FEATURE_CU_ABOUT_NEW_CONTAINER: boolean;
  FEATURE_TRANSPARENCY_COMMENTS: boolean;
  FEATURE_GLOBAL_ACTIVITIES: boolean;
  FEATURE_AUTH: boolean;
}
