import type { Roadmap } from '@/core/models/interfaces/roadmaps';

export const headerCardData = {
  title: 'MakerDAO Dashboard',
  description:
    "Welcome to the MakerDAO Dashboard, your hub for key insights into MakerDAO's finances, governance, teams, and roadmaps. Get up-to-date data and explore strategic developments to stay informed about MakerDAO’s progress and future plans.",
  buttonTexts: ['Finances', 'Governance', 'Contributors', 'Roadmap'],
  buttonLinks: ['#finances', '#governance', '#contributors', '#roadmap'],
  buttonShadows: [
    '1px 4px 15px 0px rgba(19, 83, 36, 1)',
    '1px 4px 15px 0px rgba(19, 83, 36, 1)',
    '1px 4px 15px 0px rgba(188, 153, 242, 0.2)',
    '1px 4px 15px 0px rgba(188, 153, 242, 0.5)',
    '1px 4px 15px 0px rgba(25, 144, 255, 0.2)',
    '1px 4px 15px 0px rgba(25, 144, 255, 0.5)',
    '1px 4px 15px 0px rgba(234, 67, 53, 0.2)',
    '1px 4px 15px 0px rgba(234, 67, 53, 0.5)',
  ],
};

export const sectionsData = {
  titles: ['Finances', 'Governance', 'Contributors', 'Roadmap'],
};

export const financesBarChartCardData = {
  title: 'MakerDAO Finances',
  annualProfitLegendAsteriskText: '*All values are converted to DAI',
  annualProfitLegendTitle: 'Annual Profit',
  revenueLegendTitle: 'Revenue',
  revenueLegendButtonTexts: ['Fees', 'Liquidation Income', 'PSM'],
  spendingLegendTitle: 'Spending',
  spendingLegendButtonTexts: ['DAI Spent', 'MKR Vesting'],
  makerburnLinkText: 'makerburn.com',
  detailsLinkText: 'Details',
};

export const financesLineChartCardData = {
  tabButtonsTexts: ['Realized Expenses', 'Operational Reserves', 'Forecast'],
};

export const roadmapsData: Roadmap[] = [
  {
    id: 'r1',
    title: 'Phase 1',
    description: 'Phase 1 MakerDAO roadmap.',
    milestones: [
      {
        title: 'Phase 1 - Milestone 1',
        id: '',
        sequenceCode: '',
        code: '',
        abstract: '',
        description: '',
        targetDate: '',
        scope: {
          deliverables: [],
          status: null,
          progress: null,
          totalDeliverables: null,
          deliverablesCompleted: null,
        },
        coordinators: [],
        contributors: [],
      },
      {
        title: 'Phase 1 - Milestone 2',
        id: '',
        sequenceCode: '',
        code: '',
        abstract: '',
        description: '',
        targetDate: '',
        scope: {
          deliverables: [],
          status: null,
          progress: null,
          totalDeliverables: null,
          deliverablesCompleted: null,
        },
        coordinators: [],
        contributors: [],
      },
      {
        title: 'Phase 1 - Milestone 3',
        id: '',
        sequenceCode: '',
        code: '',
        abstract: '',
        description: '',
        targetDate: '',
        scope: {
          deliverables: [],
          status: null,
          progress: null,
          totalDeliverables: null,
          deliverablesCompleted: null,
        },
        coordinators: [],
        contributors: [],
      },
      {
        title: 'Phase 1 - Milestone 4',
        id: '',
        sequenceCode: '',
        code: '',
        abstract: '',
        description: '',
        targetDate: '',
        scope: {
          deliverables: [],
          status: null,
          progress: null,
          totalDeliverables: null,
          deliverablesCompleted: null,
        },
        coordinators: [],
        contributors: [],
      },
      {
        title: 'Phase 1 - Milestone 5',
        id: '',
        sequenceCode: '',
        code: '',
        abstract: '',
        description: '',
        targetDate: '',
        scope: {
          deliverables: [],
          status: null,
          progress: null,
          totalDeliverables: null,
          deliverablesCompleted: null,
        },
        coordinators: [],
        contributors: [],
      },
      {
        title: 'Phase 1 - Milestone 6',
        id: '',
        sequenceCode: '',
        code: '',
        abstract: '',
        description: '',
        targetDate: '',
        scope: {
          deliverables: [],
          status: null,
          progress: null,
          totalDeliverables: null,
          deliverablesCompleted: null,
        },
        coordinators: [],
        contributors: [],
      },
      {
        title: 'Phase 1 - Milestone 7',
        id: '',
        sequenceCode: '',
        code: '',
        abstract: '',
        description: '',
        targetDate: '',
        scope: {
          deliverables: [],
          status: null,
          progress: null,
          totalDeliverables: null,
          deliverablesCompleted: null,
        },
        coordinators: [],
        contributors: [],
      },
      {
        title: 'Phase 1 - Milestone 8',
        id: '',
        sequenceCode: '',
        code: '',
        abstract: '',
        description: '',
        targetDate: '',
        scope: {
          deliverables: [],
          status: null,
          progress: null,
          totalDeliverables: null,
          deliverablesCompleted: null,
        },
        coordinators: [],
        contributors: [],
      },
      {
        title: 'Phase 1 - Milestone 9',
        id: '',
        sequenceCode: '',
        code: '',
        abstract: '',
        description: '',
        targetDate: '',
        scope: {
          deliverables: [],
          status: null,
          progress: null,
          totalDeliverables: null,
          deliverablesCompleted: null,
        },
        coordinators: [],
        contributors: [],
      },
      {
        title: 'Phase 1 - Milestone 10',
        id: '',
        sequenceCode: '',
        code: '',
        abstract: '',
        description: '',
        targetDate: '',
        scope: {
          deliverables: [],
          status: null,
          progress: null,
          totalDeliverables: null,
          deliverablesCompleted: null,
        },
        coordinators: [],
        contributors: [],
      },
    ],
    slug: '',
  },
  {
    id: 'r2',
    title: 'Phase 2',
    description: 'Phase 2 MakerDAO roadmap.',
    milestones: [
      {
        title: 'Phase 2 - Milestone 1',
        id: '',
        sequenceCode: '',
        code: '',
        abstract: '',
        description: '',
        targetDate: '',
        scope: {
          deliverables: [],
          status: null,
          progress: null,
          totalDeliverables: null,
          deliverablesCompleted: null,
        },
        coordinators: [],
        contributors: [],
      },
      {
        title: 'Phase 2 - Milestone 2',
        id: '',
        sequenceCode: '',
        code: '',
        abstract: '',
        description: '',
        targetDate: '',
        scope: {
          deliverables: [],
          status: null,
          progress: null,
          totalDeliverables: null,
          deliverablesCompleted: null,
        },
        coordinators: [],
        contributors: [],
      },
      {
        title: 'Phase 2 - Milestone 3',
        id: '',
        sequenceCode: '',
        code: '',
        abstract: '',
        description: '',
        targetDate: '',
        scope: {
          deliverables: [],
          status: null,
          progress: null,
          totalDeliverables: null,
          deliverablesCompleted: null,
        },
        coordinators: [],
        contributors: [],
      },
      {
        title: 'Phase 2 - Milestone 4',
        id: '',
        sequenceCode: '',
        code: '',
        abstract: '',
        description: '',
        targetDate: '',
        scope: {
          deliverables: [],
          status: null,
          progress: null,
          totalDeliverables: null,
          deliverablesCompleted: null,
        },
        coordinators: [],
        contributors: [],
      },
      {
        title: 'Phase 2 - Milestone 5',
        id: '',
        sequenceCode: '',
        code: '',
        abstract: '',
        description: '',
        targetDate: '',
        scope: {
          deliverables: [],
          status: null,
          progress: null,
          totalDeliverables: null,
          deliverablesCompleted: null,
        },
        coordinators: [],
        contributors: [],
      },
      {
        title: 'Phase 2 - Milestone 6',
        id: '',
        sequenceCode: '',
        code: '',
        abstract: '',
        description: '',
        targetDate: '',
        scope: {
          deliverables: [],
          status: null,
          progress: null,
          totalDeliverables: null,
          deliverablesCompleted: null,
        },
        coordinators: [],
        contributors: [],
      },
    ],
    slug: '',
  },
  {
    id: 'r3',
    title: 'Phase 3',
    description: 'Phase 3 MakerDAO roadmap.',
    milestones: [
      {
        title: 'Phase 3 - Milestone 1',
        id: '',
        sequenceCode: '',
        code: '',
        abstract: '',
        description: '',
        targetDate: '',
        scope: {
          deliverables: [],
          status: null,
          progress: null,
          totalDeliverables: null,
          deliverablesCompleted: null,
        },
        coordinators: [],
        contributors: [],
      },
      {
        title: 'Phase 3 - Milestone 2',
        id: '',
        sequenceCode: '',
        code: '',
        abstract: '',
        description: '',
        targetDate: '',
        scope: {
          deliverables: [],
          status: null,
          progress: null,
          totalDeliverables: null,
          deliverablesCompleted: null,
        },
        coordinators: [],
        contributors: [],
      },
      {
        title: 'Phase 3 - Milestone 3',
        id: '',
        sequenceCode: '',
        code: '',
        abstract: '',
        description: '',
        targetDate: '',
        scope: {
          deliverables: [],
          status: null,
          progress: null,
          totalDeliverables: null,
          deliverablesCompleted: null,
        },
        coordinators: [],
        contributors: [],
      },
      {
        title: 'Phase 3 - Milestone 4',
        id: '',
        sequenceCode: '',
        code: '',
        abstract: '',
        description: '',
        targetDate: '',
        scope: {
          deliverables: [],
          status: null,
          progress: null,
          totalDeliverables: null,
          deliverablesCompleted: null,
        },
        coordinators: [],
        contributors: [],
      },
    ],
    slug: '',
  },
];
